In [1]:
from skimage import data, draw,color, data, restoration
from skimage import transform, util
from scipy import misc, fftpack, signal, ndimage
import numpy as np
from numpy.linalg import inv
from skimage import filters, color
from matplotlib import pyplot as plt
from PIL import Image, ImageDraw, ImageEnhance
import matplotlib.animation as animation
from scipy.misc import imresize
from scipy import ndimage as nd
import scipy

In [2]:
scale = 5
rgb =  plt.imread('casa.jpg')
rgb = imresize(rgb, ( rgb.shape[0]/scale,rgb.shape[1]/scale,3),interp='bilinear')
img_LAB = color.rgb2lab(rgb.astype('float'))
img_gris = color.rgb2gray(rgb)
print img_gris.shape
print rgb.shape
fig = plt.figure(121) 
plt.imshow(rgb)
plt.title('Original Image')
fig = plt.figure(122) 
plt.imshow(img_LAB[:,:,2])
plt.title('Gray image')
plt.show()

(96, 128)
(96, 128, 3)


In [3]:
def gradient(img):
    img = color.rgb2gray(img)
    gx, gy = np.gradient(img)
    grad = np.sqrt(gx*gx + gy*gy)
    return grad
grad = gradient(img_gris)
#normalitzacio d'imatge
def normalitzar(imatge):
    return np.real((imatge - np.min(imatge)) * 256 / (np.max(imatge) - np.min(imatge)))

In [4]:
#normalitzo les imatges a 255
rgb=normalitzar(rgb)
img_gris=normalitzar(img_gris)
img_grad=gradient(rgb)
img_grad=normalitzar(img_grad)
print img_grad.shape
plt.imshow(rgb.astype('uint8'))
plt.title('Original Image')
fig = plt.figure(122) 
plt.imshow(img_gris.astype('uint8'),cmap="gray")
plt.title('Gray image')
fig = plt.figure(123) 
plt.imshow(img_grad.astype('uint8'),cmap="gray")
plt.title('Contorn')
plt.show()

(96, 128)


In [19]:
class get_mouse_click():
    
    #Mouse interaction interface for radial distortion removal.
    def __init__(self, img):
      height, width = img.shape[:2]
      self.figure = plt.imshow(img, extent=(0, width, height, 0))
      plt.gray()
      plt.title('select the object to remove')
      plt.xlabel('Select sets of  points with left mouse button,\n'
                 'click right button to close the polygon.')
      plt.connect('button_press_event', self.button_press)
      plt.connect('motion_notify_event', self.mouse_move)

      self.img = np.atleast_3d(img)
      self.points = []
      self.centre = np.array([(width - 1)/2., (height - 1)/2.])

      self.height = height
      self.width = width

      self.make_cursorline()
      self.figure.axes.set_autoscale_on(False)

      plt.show()
      plt.close()

    def make_cursorline(self):
        self.cursorline, = plt.plot([0],[0],'r:+', linewidth=2,markersize=15,markeredgecolor='b')

    def button_press(self,event):
        # Register mouse clicks.
        if (event.button == 1 and event.xdata and event.ydata):
            self.points.append((event.xdata,event.ydata))
            plt.gca().lines.append(self.cursorline)
            plt.gca()
            self.make_cursorline()
        if (event.button != 1):
            self.points.append((self.points[0][0],self.points[0][1]))
            plt.close()
            return self.points

    def mouse_move(self,event):
        # Handle cursor drawing.
        pts_last_set=len(self.points)
        pts = np.zeros((pts_last_set+1,2))
        if pts_last_set > 0:
            # Line follows up to 3 clicked points:
            pts[:pts_last_set] = self.points[-pts_last_set:]
            # The last point of the line follows the mouse cursor
        pts[pts_last_set:] = [event.xdata,event.ydata]
        self.cursorline.set_data(pts[:,0], pts[:,1])
        plt.draw()
def compute_mask(width,height,polygon):
    
    img = Image.new('L', (width, height), 0)
    ImageDraw.Draw(img).polygon(polygon, outline=1, fill=1)
    mask = np.array(img)
    #mask100 = 100*np.ones([mask.shape[0],mask.shape[1]])
    #mask=mask*101
    #mask = 1. - mask; # switch 0s and 1s
    return mask
def convine_mask(zona_delete,img_gris):
    #si tenim 1 a la macara tenim forat
    for i in xrange(len(img_gris)):
        for j in xrange(len(img_gris[0])):
            if zona_delete[i][j]==1:
                img_gris[i][j]=-100
    return img_gris
def buscar_pix(img,t,r,finestra):   
    for i in xrange(len(img)):
        for j in xrange(len(img[0])):
            
            if img[i][j]!=-100:
                #if img[i][j]-img[t][r]<=0.1 and grad[i][j]-grad[t][r]<=0.1:
                if img[i][j]-img[t][r]<=0.8:
                    pix=(img[i][j]+img[i-1][j-1]+img[i-1][j]+img[i][j-1])/4
                    #print "t,r",img_mask[t][r]
                    #print "i,j",img_mask[i][j]
                    return pix
def millors_pix(finestra,finestra2,img_gris,t,r):
    print finestra.shape
    print finestra2.shape
    #aqui fariem el calcul de la formula explicada pel professor
    #1/numero de 1 de la mascara*(Ixy-Fxy)² ssd = float(np.sum((img_gris[:,:,0:3] - finestra[:,:,0:3])**2))

    ssd = float(np.sum(finestra2*(img_gris[i-4:i+4,i-4:i+4] - finestra[:,:])**2))
    print finestra2
    return (1/sum(finestra2))*ssd

In [20]:
rdi = get_mouse_click(img_gris.astype('uint8'))
height,width=img_gris.shape
zona_delete = compute_mask(width,height,rdi.points)
zona_delete_erosio=ndimage.binary_erosion(zona_delete)
#calculo el primer contorn a substituir restant la mascara menys ella mateixa erosionada
delete_ceva =zona_delete - zona_delete_erosio 
finestra = np.zeros((8,8))
finestra2 = np.ones((8,8), dtype=np.int)
img_gris_convine=convine_mask(zona_delete,img_gris)
for i in xrange(len(delete_ceva)):
    for j in xrange(len(delete_ceva[0])):
        if delete_ceva[i][j]==1:
            print i,j
            finestra=zona_delete[i-4:i+4,j-4:j+4]
            #finestra2 per multiplicar on tenim 0 on hi haura el forat
            finestra2=abs(finestra-finestra2)
            #finestra_retorna=funcio que retornara la finestra mes similar
            ssd=millors_pix(finestra,finestra2,img_gris_convine,i,j)


44 108
(8, 8)
(8, 8)
[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 0 0 0 1]
 [1 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0]]
44 109
(8, 8)
(8, 8)
[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 0 1 1 0 1]
 [0 1 1 1 1 1 1 0]
 [1 0 1 1 1 1 1 0]
 [1 1 1 0 1 1 1 1]]
44 110
(8, 8)
(8, 8)
[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 0 1 0 1 0 1]
 [1 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 1 0]
 [1 1 0 1 0 0 0 1]]
45 105
(8, 8)
(8, 8)
[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 0]
 [1 1 0 1 1 0 1 0]
 [1 0 0 0 0 1 0 1]
 [0 1 0 0 0 0 1 1]
 [1 1 0 1 0 0 0 1]]
45 106
(8, 8)
(8, 8)
[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 0 1]
 [1 1 0 0 0 1 0 1]
 [1 0 0 0 1 0 1 0]
 [0 1 0 0 0 0 0 0]
 [1 1 0 1 0 0 0 0]]
45 107
(8, 8)
(8, 8)
[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 0 1 0]
 [1 1 1 1 1 0 1 0]
 [1 0 0 1 0 1 

In [14]:
#finestra de 9x9
print finestra.shape

(8, 8)


In [4]:
for i in xrange(5,9):
    for j in xrange(5,9):
        print i,j


5 5
5 6
5 7
5 8
6 5
6 6
6 7
6 8
7 5
7 6
7 7
7 8
8 5
8 6
8 7
8 8


500


In [ ]:
#codigos de pruevas

img_mask = convine_mask(zona_delete,img_gris)
finestra=5
print np.min(zona_delete)
cont = 0
for i in xrange(len(img_mask)):
    for j in xrange(len(img_mask[0])):
        if img_mask[i][j]==-100:
            #faltaria fer que compari el valor del gradient i el valor del pixel
            t,r= buscar_pix(img_mask,i,j-1,finestra)

            img_mask[i][j]=img_mask[t][r]
            #img_mask[i-5:i+5,j-5:j+5]=part
            #img_mask[i-5:i+5][j-5:j+5]=img_mask[t-5:j+5][r-5:j+5]
            #misc.imsave('imatges/'+str(cont+1)+'.png', img_mask)
            #cont  += 1




plt.imshow(img_mask)
plt.title('img_mask')
plt.show()


print len(img_gris[0])


def bucarpath(img,finestra,t,r):
    path = np.zeros((finestra*2,finestra*2))
    path = img[t-finestra:t+finestra,r-finestra:r+finestra]
    return path
prova=bucarpath(img_gris,5,275,439)
fig = plt.figure(123) 
plt.imshow(img_gris,cmap="gray")
plt.title('img_mask')

sub=bucarpath(img_gris,5,238,413)
img_gris[275-5:275+5,429-5:429+5]=sub
fig = plt.figure(124) 
plt.imshow(img_gris,cmap="gray")
plt.title('img_mask')
plt.show()